[package]
name = "git"
version = "0.1.0"
authors = ["Chris Dickinson <christopher.s.dickinson@gmail.com>"]

[dependencies]
hex = "0.3.1"
glob = "0.2.11"
regex = "0.2.3"
flate2 = "1.0.1"
multimap = "0.4.0"
byteorder = "1.2.1"
lazy_static = "1.0.0"
